// ArogyaSetu AI — Regional Multilingual Translation Service
// Translates application interface into regional Indian languages while strictly preserving proper nouns
// (e.g. "ArogyaSetu AI", "Khordha", "Jatni", "Balipatna", "Begunia", "Banapur", "Tangi", "Anti-Snake Venom", "Oxytocin", "Insulin", "NHM", "IMD", "ISRO")

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', nativeName: 'English' },
  { code: 'hi', label: 'Hindi', nativeName: 'हिन्दी (Hindi)' },
  { code: 'or', label: 'Odia', nativeName: 'ଓଡ଼ିଆ (Odia)' },
  { code: 'bn', label: 'Bengali', nativeName: 'বাংলা (Bengali)' },
  { code: 'te', label: 'Telugu', nativeName: 'తెలుగు (Telugu)' },
  { code: 'ta', label: 'Tamil', nativeName: 'தமிழ் (Tamil)' }
];

export const TRANSLATIONS = {
  en: {
    selectLanguage: "Select Language",
    brandTrack: "Track 2 · Healthcare",
    brandTagline: "Predictive Medicine Supply Chain & Clinic Intelligence for Rural India",
    cmoRoleTitle: "Chief Medical Officer (CMO) · District Authority Session",
    pharmacistRoleTitle: "PHC Dispensary Pharmacist · Local Inventory Session",
    ashaRoleTitle: "ASHA Community Health Worker · Bedside Field Session",
    logout: "Logout",
    pitchDeck: "Pitch Deck",
    googleAi: "Google AI",
    home: "Home",
    allViews: "All Views",
    gisMap: "District GIS Network & Cold-Chain Route",
    facilitiesOversight: "District Facilities Oversight",
    medicineLedger: "Detailed Medicine Ledger",
    agenticRecommender: "Autonomous Agentic AI Borrow Recommender",
    federatedGrid: "Federated National Grid (Beds, Staff & Cross-State AI)",
    selectCenter: "Select Center:",
    safeBuffer: "Safe Buffer",
    lowStock: "Low Stock",
    stockoutAlert: "Stockout Alert",
    courierInTransit: "Courier in Transit",
    orderOfficials: "Order Officials to Send Medicines ASAP",
    printTransitChallan: "Print Transit Challan",
    status: "Status",
    inCharge: "In-charge",
    distance: "Distance",
    coldChainFridge: "Cold Chain Fridge",
    optimal: "Optimal",
    scanMedicine: "Scan Medicine",
    enterStockCount: "Count of Stock Arrived (Units):",
    enterQuantityPrompt: "AI auto-filled Medicine Name & Batch from camera. Please enter physical quantity arrived:",
    confirmIntake: "Confirm & Commit Stock to Pharmacy Ledger",
    publicDataFeeds: "Public Government Data Feeds",
    forecasterTitle: "Predictive Demand & Epidemiological Outbreak Forecaster",
    askChatbot: "Ask ArogyaSetu AI Copilot",
    typeYourQuery: "Ask any question about medicines, beds, stockouts, or protocols...",
    listening: "Listening to your voice...",
    voiceSearch: "Voice Input",
    send: "Send",
    close: "Close"
  },
  hi: {
    selectLanguage: "भाषा चुनें",
    brandTrack: "ट्रैक 2 · स्वास्थ्य सेवा",
    brandTagline: "ग्रामीण भारत के लिए पूर्वानुमानित दवा आपूर्ति श्रृंखला और क्लिनिक बुद्धिमत्ता",
    cmoRoleTitle: "मुख्य चिकित्सा अधिकारी (CMO) · जिला प्राधिकरण सत्र",
    pharmacistRoleTitle: "PHC औषधालय फार्मासिस्ट · स्थानीय इन्वेंटरी सत्र",
    ashaRoleTitle: "ASHA सामुदायिक स्वास्थ्य कार्यकर्ता · फील्ड सत्र",
    logout: "लॉगआउट",
    pitchDeck: "पिच डेक",
    googleAi: "Google AI",
    home: "होम",
    allViews: "सभी दृश्य",
    gisMap: "जिला GIS नेटवर्क एवं कोल्ड-चेन रूट",
    facilitiesOversight: "जिला स्वास्थ्य केंद्र निगरानी",
    medicineLedger: "विस्तृत दवा रजिस्टर",
    agenticRecommender: "स्वायत्त एजेंटिक AI दवा स्थानांतरण",
    federatedGrid: "राष्ट्रीय संघीय ग्रिड (बेड, स्टाफ एवं राज्य AI)",
    selectCenter: "केंद्र चुनें:",
    safeBuffer: "सुरक्षित स्टॉक",
    lowStock: "कम स्टॉक",
    stockoutAlert: "स्टॉक समाप्त चेतावनी",
    courierInTransit: "कूरियर मार्ग में है",
    orderOfficials: "अधिकारियों को तुरंत दवाएं भेजने का आदेश दें",
    printTransitChallan: "पारगमन चालान प्रिंट करें",
    status: "स्थिति",
    inCharge: "प्रभारी",
    distance: "दूरी",
    coldChainFridge: "कोल्ड चेन फ्रिज",
    optimal: "इष्टतम",
    scanMedicine: "दवा स्कैन करें",
    enterStockCount: "आए हुए स्टॉक की संख्या (इकाइयां):",
    enterQuantityPrompt: "AI ने फोटो से दवा का नाम व बैच अपने आप भर दिया है। कृपया प्राप्त इकाइयों की संख्या दर्ज करें:",
    confirmIntake: "पुष्टि करें और फार्मेसी रजिस्टर में स्टॉक जोड़ें",
    publicDataFeeds: "सार्वजनिक सरकारी डेटा फ़ीड्स (IMD, ISRO, WHO, data.gov.in)",
    forecasterTitle: "पूर्वानुमानित मांग एवं महामारी प्रकोप विश्लेषक",
    askChatbot: "ArogyaSetu AI सहायक से पूछें",
    typeYourQuery: "दवाओं, बेड, स्टॉक या आपातकालीन प्रोटोकॉल के बारे में पूछें...",
    listening: "आपकी आवाज़ सुन रहे हैं...",
    voiceSearch: "आवाज़ इनपुट",
    send: "भेजें",
    close: "बंद करें"
  },
  or: {
    selectLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    brandTrack: "ଟ୍ରାକ୍ ୨ · ସ୍ୱାସ୍ଥ୍ୟସେବା",
    brandTagline: "ଗ୍ରାମୀଣ ଭାରତ ପାଇଁ ଭବିଷ୍ୟବାଣୀ ଔଷଧ ଯୋଗାଣ ଶୃଙ୍ଖଳା ଓ କ୍ଲିନିକ ବୁଦ୍ଧିମତା",
    cmoRoleTitle: "ମୁଖ୍ୟ ଚିକିତ୍ସା ଅଧିକାରୀ (CMO) · ଜିଲ୍ଲା କର୍ତ୍ତୃପକ୍ଷ ଅଧିବେଶନ",
    pharmacistRoleTitle: "PHC ଔଷଧାଳୟ ଫାର୍ମାସିଷ୍ଟ · ସ୍ଥାନୀୟ ଇନଭେଣ୍ଟୋରୀ ଅଧିବେଶନ",
    ashaRoleTitle: "ASHA କର୍ମୀ · କ୍ଷେତ୍ରସ୍ତରୀୟ ଅଧିବେଶନ",
    logout: "ଲଗ୍ଆଉଟ୍",
    pitchDeck: "ପିଚ୍ ଡେକ୍",
    googleAi: "Google AI",
    home: "ମୁଖ୍ୟ ପୃଷ୍ଠା",
    allViews: "ସମସ୍ତ ଦୃଶ୍ୟ",
    gisMap: "ଜିଲ୍ଲା GIS ନେଟୱାର୍କ ଏବଂ କୋଲ୍ଡ-ଚେନ୍ ରୁଟ୍",
    facilitiesOversight: "ଜିଲ୍ଲା ସ୍ୱାସ୍ଥ୍ୟ କେନ୍ଦ୍ର ତଦାରଖ",
    medicineLedger: "ବିସ୍ତୃତ ଔଷଧ ରେଜିଷ୍ଟର",
    agenticRecommender: "ସ୍ୱୟଂଚାଳିତ AI ଔଷଧ ହସ୍ତାନ୍ତର ପରାମର୍ଶଦାତା",
    federatedGrid: "ଜାତୀୟ ଫେଡେରେଟେଡ୍ ଗ୍ରିଡ୍ (ଶଯ୍ୟା, କର୍ମଚାରୀ ଓ ରାଜ୍ୟ AI)",
    selectCenter: "କେନ୍ଦ୍ର ବାଛନ୍ତୁ:",
    safeBuffer: "ସୁରକ୍ଷିତ ଷ୍ଟକ୍",
    lowStock: "କମ୍ ଷ୍ଟକ୍",
    stockoutAlert: "ଷ୍ଟକ୍ ଶେଷ ସତର୍କତା",
    courierInTransit: "କୁରିୟର ବାଟରେ ଅଛି",
    orderOfficials: "ତୁରନ୍ତ ଔଷଧ ପଠାଇବାକୁ ଅଧିକାରୀଙ୍କୁ ନିର୍ଦ୍ଦେଶ ଦିଅନ୍ତୁ",
    printTransitChallan: "ଟ୍ରାଞ୍ଜିଟ୍ ଚାଲାଣ ପ୍ରିଣ୍ଟ କରନ୍ତୁ",
    status: "ସ୍ଥିତି",
    inCharge: "ପ୍ରଭାରୀ",
    distance: "ଦୂରତା",
    coldChainFridge: "କୋଲ୍ଡ ଚେନ୍ ଫ୍ରିଜ୍",
    optimal: "ସଠିକ୍",
    scanMedicine: "ଔଷଧ ସ୍କାନ କରନ୍ତୁ",
    enterStockCount: "ପହଞ୍ଚିଥିବା ଷ୍ଟକ୍ ସଂଖ୍ୟା (ୟୁନିଟ୍):",
    enterQuantityPrompt: "AI ଫଟୋରୁ ଔଷଧ ନାମ ଓ ବ୍ୟାଚ୍ ଭରିଦେଇଛି। ଦୟାକରି ଆସିଥିବା ସଂଖ୍ୟା ଲେଖନ୍ତୁ:",
    confirmIntake: "ନିଶ୍ଚିତ କରନ୍ତୁ ଓ ଫାର୍ମାସି ରେଜିଷ୍ଟରରେ ଯୋଡନ୍ତୁ",
    publicDataFeeds: "ସରକାରୀ ଡାଟା ଫିଡ୍ (IMD, ISRO, WHO, data.gov.in)",
    forecasterTitle: "ପୂର୍ବାନୁମାନିତ ଚାହିଦା ଓ ମହାମାରୀ ଆକଳନ",
    askChatbot: "ArogyaSetu AI ସହାୟକଙ୍କୁ ପଚାରନ୍ତୁ",
    typeYourQuery: "ଔଷଧ, ବେଡ୍, ଷ୍ଟକ୍ କିମ୍ବା ପ୍ରୋଟୋକଲ୍ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    listening: "ଆପଣଙ୍କ ସ୍ୱର ଶୁଣୁଛୁ...",
    voiceSearch: "ଭଏସ୍ ଇନପୁଟ୍",
    send: "ପଠାନ୍ତୁ",
    close: "ବନ୍ଦ କରନ୍ତୁ"
  },
  bn: {
    selectLanguage: "ভাষা নির্বাচন করুন",
    brandTrack: "ট্র্যাক ২ · স্বাস্থ্যসেবা",
    brandTagline: "গ্রামীণ ভারতের জন্য পূর্বাভাসমূলক ওষুধ সরবরাহ শৃঙ্খল ও ক্লিনিক বুদ্ধিমত্তা",
    cmoRoleTitle: "প্রধান চিকিৎসা কর্মকর্তা (CMO) · জেলা কর্তৃপক্ষ সেশন",
    pharmacistRoleTitle: "PHC ডিসপেনসারি ফার্মাসিস্ট · স্থানীয় ইনভেন্টরি সেশন",
    ashaRoleTitle: "ASHA স্বাস্থ্যকর্মী · মাঠ পর্যায়ের সেশন",
    logout: "লগআউট",
    pitchDeck: "পিচ ডেক",
    googleAi: "Google AI",
    home: "হোম",
    allViews: "সব দৃশ্য",
    gisMap: "জেলা GIS নেটওয়ার্ক ও কোল্ড-চেইন রুট",
    facilitiesOversight: "জেলা স্বাস্থ্যকেন্দ্র পর্যবেক্ষণ",
    medicineLedger: "বিস্তারিত ওষুধ রেজিস্টার",
    agenticRecommender: "স্বায়ত্তশাসিত AI ওষুধ স্থানান্তর সুপারিশকারী",
    federatedGrid: "জাতীয় ফেডারেল গ্রিড (শয্যা, কর্মী ও আন্তঃরাজ্য AI)",
    selectCenter: "কেন্দ্র নির্বাচন করুন:",
    safeBuffer: "নিরাপদ স্টক",
    lowStock: "স্বল্প স্টক",
    stockoutAlert: "স্টক শেষ সতর্কতা",
    courierInTransit: "কুরিয়ার পথে রয়েছে",
    orderOfficials: "কর্মকর্তাদের দ্রুত ওষুধ পাঠানোর নির্দেশ দিন",
    printTransitChallan: "ট্রানজিট চালান প্রিন্ট করুন",
    status: "অবস্থা",
    inCharge: "ভারপ্রাপ্ত",
    distance: "দূরত্ব",
    coldChainFridge: "কোল্ড চেইন ফ্রিজ",
    optimal: "অনুকূল",
    scanMedicine: "ওষুধ স্ক্যান করুন",
    enterStockCount: "আগত স্টকের সংখ্যা (ইউনিট):",
    enterQuantityPrompt: "AI ছবি থেকে ওষুধের নাম ও ব্যাচ পূরণ করেছে। অনুগ্রহ করে মোট সংখ্যা লিখুন:",
    confirmIntake: "নিশ্চিত করুন এবং ফার্মেসি লেজারে যোগ করুন",
    publicDataFeeds: "সরকারি ডেটা ফিড (IMD, ISRO, WHO, data.gov.in)",
    forecasterTitle: "পূর্বাভাসমূলক চাহিদা এবং মহামারী প্রাদুর্ভাব পূর্বাভাস",
    askChatbot: "ArogyaSetu AI সহায়ককে জিজ্ঞাসা করুন",
    typeYourQuery: "ওষুধ, শয্যা, ঘাটতি বা জরুরি প্রোটোকল সম্পর্কে জিজ্ঞাসা করুন...",
    listening: "আপনার ভয়েস শুনছি...",
    voiceSearch: "ভয়েস ইনপুট",
    send: "পাঠান",
    close: "বন্ধ করুন"
  },
  te: {
    selectLanguage: "భాషను ఎంచుకోండి",
    brandTrack: "ట్రాక్ 2 · ఆరోగ్య సంరక్షణ",
    brandTagline: "గ్రామీణ భారతదేశం కోసం ప్రిడిక్టివ్ మెడిసిన్ సరఫరా గొలుసు & క్లినిక్ ఇంటెలిజెన్స్",
    cmoRoleTitle: "చీఫ్ మెడికల్ ఆఫీసర్ (CMO) · జిల్లా అథారిటీ సెషన్",
    pharmacistRoleTitle: "PHC డిస్పెన్సరీ ఫార్మసిస్ట్ · లోకల్ ఇన్వెంటరీ సెషన్",
    ashaRoleTitle: "ASHA కమ్యూనిటీ హెల్త్ వర్కర్ · ఫీల్డ్ సెషన్",
    logout: "లాగ్అవుట్",
    pitchDeck: "పిచ్ డెక్",
    googleAi: "Google AI",
    home: "హోమ్",
    allViews: "అన్ని వీక్షణలు",
    gisMap: "జిల్లా GIS నెట్‌వర్క్ & కోల్డ్-చైన్ రూట్",
    facilitiesOversight: "జిల్లా సౌకర్యాల పర్యవేక్షణ",
    medicineLedger: "సవివరమైన మందుల రిజిస్టర్",
    agenticRecommender: "స్వయంప్రతిపత్తి AI ఔషధ బదిలీ సిఫార్సుదారు",
    federatedGrid: "నేషనల్ ఫెడరేటెడ్ గ్రిడ్ (బెడ్లు, సిబ్బంది & స్టేట్ AI)",
    selectCenter: "కేంద్రాన్ని ఎంచుకోండి:",
    safeBuffer: "సురక్షిత నిల్వ",
    lowStock: "తక్కువ నిల్వ",
    stockoutAlert: "స్టాక్ కొరత హెచ్చరిక",
    courierInTransit: "కొరియర్ మార్గంలో ఉంది",
    orderOfficials: "వెంటనే మందులు పంపాలని అధికారులను ఆదేశించండి",
    printTransitChallan: "రవాణా చలాన్ ప్రింట్ చేయండి",
    status: "స్థితి",
    inCharge: "ఇన్-ఛార్జ్",
    distance: "దూరం",
    coldChainFridge: "కోల్డ్ చైన్ ఫ్రిజ్",
    optimal: "సరైనది",
    scanMedicine: "మందును స్కాన్ చేయండి",
    enterStockCount: "వచ్చిన స్టాక్ సంఖ్య (యూనిట్లు):",
    enterQuantityPrompt: "AI ఫోటో నుండి మందు పేరు & బ్యాచ్‌ను నింపింది. దయచేసి అందిన పరిమాణాన్ని నమోదు చేయండి:",
    confirmIntake: "నిర్ధారించండి మరియు ఫార్మసీ రిజిస్టర్‌లో చేర్చండి",
    publicDataFeeds: "ప్రభుత్వ పబ్లిక్ డేటా ఫీడ్స్ (IMD, ISRO, WHO, data.gov.in)",
    forecasterTitle: "డిమాండ్ ప్రిడిక్షన్ & అంటువ్యాధుల వ్యాప్తి విశ్లేషణ",
    askChatbot: "ArogyaSetu AI అసిస్టెంట్‌ను అడగండి",
    typeYourQuery: "మందులు, బెడ్లు, కొరత లేదా ప్రోటోకాల్స్ గురించి అడగండి...",
    listening: "మీ స్వరాన్ని వింటున్నాము...",
    voiceSearch: "వాయిస్ ఇన్‌పుట్",
    send: "పంపండి",
    close: "మూసివేయి"
  },
  ta: {
    selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
    brandTrack: "ட்ராக் 2 · சுகாதாரப் பாதுகாப்பு",
    brandTagline: "கிராமப்புற இந்தியாவிற்கான முன்கணிப்பு மருந்து விநியோகச் சங்கிலி & கிளினிக் நுண்ணறிவு",
    cmoRoleTitle: "தலைமை மருத்துவ அலுவலர் (CMO) · மாவட்ட அமர்வு",
    pharmacistRoleTitle: "PHC மருந்தக மருந்தாளர் · உள்ளூர் சரக்கு அமர்வு",
    ashaRoleTitle: "ASHA சமூக சுகாதார ஊழியர் · கள அமர்வு",
    logout: "வெளியேறு",
    pitchDeck: "பிட்ச் டெக்",
    googleAi: "Google AI",
    home: "முகப்பு",
    allViews: "அனைத்து பார்வைகள்",
    gisMap: "மாவட்ட GIS நெட்வொர்க் & கோல்ட்-செயின் பாதை",
    facilitiesOversight: "மாவட்ட சுகாதார மையங்கள் மேற்பார்வை",
    medicineLedger: "விரிவான மருந்து பதிவேடு",
    agenticRecommender: "தன்னியக்க AI மருந்து பரிமாற்ற பரிந்துரையாளர்",
    federatedGrid: "தேசிய கூட்டமைப்பு கட்டமைப்பு (படுக்கைகள், ஊழியர்கள் & AI)",
    selectCenter: "மையத்தைத் தேர்ந்தெடுக்கவும்:",
    safeBuffer: "பாதுகாப்பான இருப்பு",
    lowStock: "குறைந்த இருப்பு",
    stockoutAlert: "இருப்பு பற்றாக்குறை எச்சரிக்கை",
    courierInTransit: "கூரியர் பயணத்தில் உள்ளது",
    orderOfficials: "உடனடியாக மருந்துகளை அனுப்ப அதிகாரிகளுக்கு உத்தரவிடவும்",
    printTransitChallan: "போக்குவரத்து சலான் அச்சிடவும்",
    status: "நிலை",
    inCharge: "பொறுப்பாளர்",
    distance: "தூரம்",
    coldChainFridge: "குளிர்பதன பெட்டி",
    optimal: "சரியான நிலை",
    scanMedicine: "மருந்தை ஸ்கேன் செய்க",
    enterStockCount: "வந்தடைந்த மருந்துகளின் எண்ணிக்கை (அலகுகள்):",
    enterQuantityPrompt: "AI புகைப்படத்திலிருந்து மருந்தின் பெயர் மற்றும் பேட்ச்சை நிரப்பியுள்ளது. வந்தடைந்த எண்ணிக்கையை உள்ளிடவும்:",
    confirmIntake: "உறுதிசெய்து மருந்தக பதிவேட்டில் சேர்க்கவும்",
    publicDataFeeds: "அரசு பொது தரவு ஊட்டங்கள் (IMD, ISRO, WHO, data.gov.in)",
    forecasterTitle: "முன்கணிப்பு தேவை & நோய் பரவல் கணிப்பாளர்",
    askChatbot: "ArogyaSetu AI உதவியாளரிடம் கேளுங்கள்",
    typeYourQuery: "மருந்துகள், படுக்கைகள், இருப்பு அல்லது நெறிமுறைகள் பற்றி கேளுங்கள்...",
    listening: "உங்கள் குரலைக் கேட்கிறது...",
    voiceSearch: "குரல் உள்ளீடு",
    send: "அனுப்பு",
    close: "மூடு"
  }
};

/**
 * Returns translated string for a given key, falling back to English.
 * Proper nouns remain untranslated.
 */
export function getTranslation(langCode, key) {
  const normalizedLang = (langCode || 'en').toLowerCase().slice(0, 2);
  const langDict = TRANSLATIONS[normalizedLang] || TRANSLATIONS.en;
  return langDict[key] || TRANSLATIONS.en[key] || key;
}
